//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgenteTermico
    {
        public int AgenteTermicoId { get; set; }
        public string Nombre { get; set; }
        public string Usuariocreacion { get; set; }
        public System.DateTime Fechacreacion { get; set; }
        public string Usuariomodificacion { get; set; }
        public Nullable<System.DateTime> Fechamodificacion { get; set; }
    }
}
