//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManiobrasTerapeuticas
    {
        public int ManiobrasTerapeuticasId { get; set; }
        public int HistoricoId { get; set; }
        public int SubTramiteId { get; set; }
        public Nullable<bool> Condicion { get; set; }
        public string Usuariocreacion { get; set; }
        public System.DateTime Fechacreacion { get; set; }
        public string Usuariomodificacion { get; set; }
        public Nullable<System.DateTime> Fechamodificacion { get; set; }
    
        public virtual Historico Historico { get; set; }
        public virtual SubTramite SubTramite { get; set; }
    }
}
