//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persona()
        {
            this.Historico = new HashSet<Historico>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int PersonaId { get; set; }
        public int TipodocumentoId { get; set; }
        public string Nrodocumento { get; set; }
        public string Nombre { get; set; }
        public string Apellidopaterno { get; set; }
        public string Apellidomaterno { get; set; }
        public string Nrotelefono { get; set; }
        public Nullable<System.DateTime> Fecnacimiento { get; set; }
        public int DistritoId { get; set; }
        public string Direccion { get; set; }
        public string Ocupacion { get; set; }
        public int SexoId { get; set; }
        public string Usuariocreacion { get; set; }
        public System.DateTime Fechacreacion { get; set; }
        public string Usuariomodificacion { get; set; }
        public Nullable<System.DateTime> Fechamodificacion { get; set; }
    
        public virtual Distrito Distrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historico> Historico { get; set; }
        public virtual Sexo Sexo { get; set; }
        public virtual Tipodocumento Tipodocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
